import os
import sys
import numpy as np
import pickle as pkl
import xgboost as xgb
import mods.ROOTmanager as manager

pkl_file = '/nfs/slac/g/ldmx/users/aechavez/ldmx-sw-v3.0.0-w-container/bdt/training/bdt_train_out_0/bdt_train_out_0_weights.pkl'
model = pkl.load(open(pkl_file,'rb'))

def main():

    # Inputs and their trees and stuff
    pdict = manager.parse()
    inlist = pdict['inlist']
    outlist = pdict['outlist']
    group_labels = pdict['groupls']
    maxEvent = pdict['maxEvent']

    # Tree model to build here
    branches_info = {
            # Base variables
            'nReadoutHits':              {'rtype': int,   'default': 0 },
            'summedDet':                 {'rtype': float, 'default': 0.},
            'summedTightIso':            {'rtype': float, 'default': 0.},
            'maxCellDep':                {'rtype': float, 'default': 0.},
            'showerRMS':                 {'rtype': float, 'default': 0.},
            'xStd':                      {'rtype': float, 'default': 0.},
            'yStd':                      {'rtype': float, 'default': 0.},
            'avgLayerHit':               {'rtype': float, 'default': 0.},
            'stdLayerHit':               {'rtype': float, 'default': 0.},
            'deepestLayerHit':           {'rtype': int,   'default': 0 },
            'ecalBackEnergy':            {'rtype': float, 'default': 0.},
            # MIP Tracking variables
            'straight4':                 {'rtype': int,   'default': 0 },
            'firstNearPhLayer':          {'rtype': int,   'default': 33},
            'nNearPhHits':               {'rtype': int,   'default': 0 },
            'fullElectronTerritoryHits': {'rtype': int,   'default': 0 },
            'fullPhotonTerritoryHits':   {'rtype': int,   'default': 0 },
            'fullTerritoryRatio':        {'rtype': float, 'default': 1.},
            'electronTerritoryHits':     {'rtype': int,   'default': 0 },
            'photonTerritoryHits':       {'rtype': int,   'default': 0 },
            'TerritoryRatio':            {'rtype': float, 'default': 1.},
            'epSep':                     {'rtype': float, 'default': 0.},
            'epDot':                     {'rtype': float, 'default': 0.},
            # Longitudinal segment variables
            'energy_s1':                 {'rtype': float, 'default': 0.},
            'nHits_s1':                  {'rtype': int,   'default': 0 },
            'xMean_s1':                  {'rtype': float, 'default': 0.},
            'yMean_s1':                  {'rtype': float, 'default': 0.},
            'layerMean_s1':              {'rtype': float, 'default': 0.},
            'xStd_s1':                   {'rtype': float, 'default': 0.},
            'yStd_s1':                   {'rtype': float, 'default': 0.},
            'layerStd_s1':               {'rtype': float, 'default': 0.},
            'energy_s2':                 {'rtype': float, 'default': 0.},
            'nHits_s2':                  {'rtype': int,   'default': 0 },
            'xMean_s2':                  {'rtype': float, 'default': 0.},
            'yMean_s2':                  {'rtype': float, 'default': 0.},
            'layerMean_s2':              {'rtype': float, 'default': 0.},
            'xStd_s2':                   {'rtype': float, 'default': 0.},
            'yStd_s2':                   {'rtype': float, 'default': 0.},
            'layerStd_s2':               {'rtype': float, 'default': 0.},
            'energy_s3':                 {'rtype': float, 'default': 0.},
            'nHits_s3':                  {'rtype': int,   'default': 0 },
            'xMean_s3':                  {'rtype': float, 'default': 0.},
            'yMean_s3':                  {'rtype': float, 'default': 0.},
            'layerMean_s3':              {'rtype': float, 'default': 0.},
            'xStd_s3':                   {'rtype': float, 'default': 0.},
            'yStd_s3':                   {'rtype': float, 'default': 0.},
            'layerStd_s3':               {'rtype': float, 'default': 0.},
            # Electron RoC variables
            'eContEnergy_x1_s1':         {'rtype': float, 'default': 0.},
            'eContEnergy_x2_s1':         {'rtype': float, 'default': 0.},
            'eContEnergy_x3_s1':         {'rtype': float, 'default': 0.},
            'eContEnergy_x4_s1':         {'rtype': float, 'default': 0.},
            'eContEnergy_x5_s1':         {'rtype': float, 'default': 0.},
            'eContNHits_x1_s1':          {'rtype': int,   'default': 0 },
            'eContNHits_x2_s1':          {'rtype': int,   'default': 0 },
            'eContNHits_x3_s1':          {'rtype': int,   'default': 0 },
            'eContNHits_x4_s1':          {'rtype': int,   'default': 0 },
            'eContNHits_x5_s1':          {'rtype': int,   'default': 0 },
            'eContXMean_x1_s1':          {'rtype': float, 'default': 0.},
            'eContXMean_x2_s1':          {'rtype': float, 'default': 0.},
            'eContXMean_x3_s1':          {'rtype': float, 'default': 0.},
            'eContXMean_x4_s1':          {'rtype': float, 'default': 0.},
            'eContXMean_x5_s1':          {'rtype': float, 'default': 0.},
            'eContYMean_x1_s1':          {'rtype': float, 'default': 0.},
            'eContYMean_x2_s1':          {'rtype': float, 'default': 0.},
            'eContYMean_x3_s1':          {'rtype': float, 'default': 0.},
            'eContYMean_x4_s1':          {'rtype': float, 'default': 0.},
            'eContYMean_x5_s1':          {'rtype': float, 'default': 0.},
            'eContLayerMean_x1_s1':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x2_s1':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x3_s1':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x4_s1':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x5_s1':      {'rtype': float, 'default': 0.},
            'eContXStd_x1_s1':           {'rtype': float, 'default': 0.},
            'eContXStd_x2_s1':           {'rtype': float, 'default': 0.},
            'eContXStd_x3_s1':           {'rtype': float, 'default': 0.},
            'eContXStd_x4_s1':           {'rtype': float, 'default': 0.},
            'eContXStd_x5_s1':           {'rtype': float, 'default': 0.},
            'eContYStd_x1_s1':           {'rtype': float, 'default': 0.},
            'eContYStd_x2_s1':           {'rtype': float, 'default': 0.},
            'eContYStd_x3_s1':           {'rtype': float, 'default': 0.},
            'eContYStd_x4_s1':           {'rtype': float, 'default': 0.},
            'eContYStd_x5_s1':           {'rtype': float, 'default': 0.},
            'eContLayerStd_x1_s1':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x2_s1':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x3_s1':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x4_s1':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x5_s1':       {'rtype': float, 'default': 0.},
            'eContEnergy_x1_s2':         {'rtype': float, 'default': 0.},
            'eContEnergy_x2_s2':         {'rtype': float, 'default': 0.},
            'eContEnergy_x3_s2':         {'rtype': float, 'default': 0.},
            'eContEnergy_x4_s2':         {'rtype': float, 'default': 0.},
            'eContEnergy_x5_s2':         {'rtype': float, 'default': 0.},
            'eContNHits_x1_s2':          {'rtype': int,   'default': 0 },
            'eContNHits_x2_s2':          {'rtype': int,   'default': 0 },
            'eContNHits_x3_s2':          {'rtype': int,   'default': 0 },
            'eContNHits_x4_s2':          {'rtype': int,   'default': 0 },
            'eContNHits_x5_s2':          {'rtype': int,   'default': 0 },
            'eContXMean_x1_s2':          {'rtype': float, 'default': 0.},
            'eContXMean_x2_s2':          {'rtype': float, 'default': 0.},
            'eContXMean_x3_s2':          {'rtype': float, 'default': 0.},
            'eContXMean_x4_s2':          {'rtype': float, 'default': 0.},
            'eContXMean_x5_s2':          {'rtype': float, 'default': 0.},
            'eContYMean_x1_s2':          {'rtype': float, 'default': 0.},
            'eContYMean_x2_s2':          {'rtype': float, 'default': 0.},
            'eContYMean_x3_s2':          {'rtype': float, 'default': 0.},
            'eContYMean_x4_s2':          {'rtype': float, 'default': 0.},
            'eContYMean_x5_s2':          {'rtype': float, 'default': 0.},
            'eContLayerMean_x1_s2':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x2_s2':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x3_s2':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x4_s2':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x5_s2':      {'rtype': float, 'default': 0.},
            'eContXStd_x1_s2':           {'rtype': float, 'default': 0.},
            'eContXStd_x2_s2':           {'rtype': float, 'default': 0.},
            'eContXStd_x3_s2':           {'rtype': float, 'default': 0.},
            'eContXStd_x4_s2':           {'rtype': float, 'default': 0.},
            'eContXStd_x5_s2':           {'rtype': float, 'default': 0.},
            'eContYStd_x1_s2':           {'rtype': float, 'default': 0.},
            'eContYStd_x2_s2':           {'rtype': float, 'default': 0.},
            'eContYStd_x3_s2':           {'rtype': float, 'default': 0.},
            'eContYStd_x4_s2':           {'rtype': float, 'default': 0.},
            'eContYStd_x5_s2':           {'rtype': float, 'default': 0.},
            'eContLayerStd_x1_s2':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x2_s2':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x3_s2':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x4_s2':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x5_s2':       {'rtype': float, 'default': 0.},
            'eContEnergy_x1_s3':         {'rtype': float, 'default': 0.},
            'eContEnergy_x2_s3':         {'rtype': float, 'default': 0.},
            'eContEnergy_x3_s3':         {'rtype': float, 'default': 0.},
            'eContEnergy_x4_s3':         {'rtype': float, 'default': 0.},
            'eContEnergy_x5_s3':         {'rtype': float, 'default': 0.},
            'eContNHits_x1_s3':          {'rtype': int,   'default': 0 },
            'eContNHits_x2_s3':          {'rtype': int,   'default': 0 },
            'eContNHits_x3_s3':          {'rtype': int,   'default': 0 },
            'eContNHits_x4_s3':          {'rtype': int,   'default': 0 },
            'eContNHits_x5_s3':          {'rtype': int,   'default': 0 },
            'eContXMean_x1_s3':          {'rtype': float, 'default': 0.},
            'eContXMean_x2_s3':          {'rtype': float, 'default': 0.},
            'eContXMean_x3_s3':          {'rtype': float, 'default': 0.},
            'eContXMean_x4_s3':          {'rtype': float, 'default': 0.},
            'eContXMean_x5_s3':          {'rtype': float, 'default': 0.},
            'eContYMean_x1_s3':          {'rtype': float, 'default': 0.},
            'eContYMean_x2_s3':          {'rtype': float, 'default': 0.},
            'eContYMean_x3_s3':          {'rtype': float, 'default': 0.},
            'eContYMean_x4_s3':          {'rtype': float, 'default': 0.},
            'eContYMean_x5_s3':          {'rtype': float, 'default': 0.},
            'eContLayerMean_x1_s3':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x2_s3':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x3_s3':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x4_s3':      {'rtype': float, 'default': 0.},
            'eContLayerMean_x5_s3':      {'rtype': float, 'default': 0.},
            'eContXStd_x1_s3':           {'rtype': float, 'default': 0.},
            'eContXStd_x2_s3':           {'rtype': float, 'default': 0.},
            'eContXStd_x3_s3':           {'rtype': float, 'default': 0.},
            'eContXStd_x4_s3':           {'rtype': float, 'default': 0.},
            'eContXStd_x5_s3':           {'rtype': float, 'default': 0.},
            'eContYStd_x1_s3':           {'rtype': float, 'default': 0.},
            'eContYStd_x2_s3':           {'rtype': float, 'default': 0.},
            'eContYStd_x3_s3':           {'rtype': float, 'default': 0.},
            'eContYStd_x4_s3':           {'rtype': float, 'default': 0.},
            'eContYStd_x5_s3':           {'rtype': float, 'default': 0.},
            'eContLayerStd_x1_s3':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x2_s3':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x3_s3':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x4_s3':       {'rtype': float, 'default': 0.},
            'eContLayerStd_x5_s3':       {'rtype': float, 'default': 0.},
            # Photon RoC variables
            'gContEnergy_x1_s1':         {'rtype': float, 'default': 0.},
            'gContEnergy_x2_s1':         {'rtype': float, 'default': 0.},
            'gContEnergy_x3_s1':         {'rtype': float, 'default': 0.},
            'gContEnergy_x4_s1':         {'rtype': float, 'default': 0.},
            'gContEnergy_x5_s1':         {'rtype': float, 'default': 0.},
            'gContNHits_x1_s1':          {'rtype': int,   'default': 0 },
            'gContNHits_x2_s1':          {'rtype': int,   'default': 0 },
            'gContNHits_x3_s1':          {'rtype': int,   'default': 0 },
            'gContNHits_x4_s1':          {'rtype': int,   'default': 0 },
            'gContNHits_x5_s1':          {'rtype': int,   'default': 0 },
            'gContXMean_x1_s1':          {'rtype': float, 'default': 0.},
            'gContXMean_x2_s1':          {'rtype': float, 'default': 0.},
            'gContXMean_x3_s1':          {'rtype': float, 'default': 0.},
            'gContXMean_x4_s1':          {'rtype': float, 'default': 0.},
            'gContXMean_x5_s1':          {'rtype': float, 'default': 0.},
            'gContYMean_x1_s1':          {'rtype': float, 'default': 0.},
            'gContYMean_x2_s1':          {'rtype': float, 'default': 0.},
            'gContYMean_x3_s1':          {'rtype': float, 'default': 0.},
            'gContYMean_x4_s1':          {'rtype': float, 'default': 0.},
            'gContYMean_x5_s1':          {'rtype': float, 'default': 0.},
            'gContLayerMean_x1_s1':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x2_s1':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x3_s1':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x4_s1':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x5_s1':      {'rtype': float, 'default': 0.},
            'gContXStd_x1_s1':           {'rtype': float, 'default': 0.},
            'gContXStd_x2_s1':           {'rtype': float, 'default': 0.},
            'gContXStd_x3_s1':           {'rtype': float, 'default': 0.},
            'gContXStd_x4_s1':           {'rtype': float, 'default': 0.},
            'gContXStd_x5_s1':           {'rtype': float, 'default': 0.},
            'gContYStd_x1_s1':           {'rtype': float, 'default': 0.},
            'gContYStd_x2_s1':           {'rtype': float, 'default': 0.},
            'gContYStd_x3_s1':           {'rtype': float, 'default': 0.},
            'gContYStd_x4_s1':           {'rtype': float, 'default': 0.},
            'gContYStd_x5_s1':           {'rtype': float, 'default': 0.},
            'gContLayerStd_x1_s1':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x2_s1':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x3_s1':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x4_s1':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x5_s1':       {'rtype': float, 'default': 0.},
            'gContEnergy_x1_s2':         {'rtype': float, 'default': 0.},
            'gContEnergy_x2_s2':         {'rtype': float, 'default': 0.},
            'gContEnergy_x3_s2':         {'rtype': float, 'default': 0.},
            'gContEnergy_x4_s2':         {'rtype': float, 'default': 0.},
            'gContEnergy_x5_s2':         {'rtype': float, 'default': 0.},
            'gContNHits_x1_s2':          {'rtype': int,   'default': 0 },
            'gContNHits_x2_s2':          {'rtype': int,   'default': 0 },
            'gContNHits_x3_s2':          {'rtype': int,   'default': 0 },
            'gContNHits_x4_s2':          {'rtype': int,   'default': 0 },
            'gContNHits_x5_s2':          {'rtype': int,   'default': 0 },
            'gContXMean_x1_s2':          {'rtype': float, 'default': 0.},
            'gContXMean_x2_s2':          {'rtype': float, 'default': 0.},
            'gContXMean_x3_s2':          {'rtype': float, 'default': 0.},
            'gContXMean_x4_s2':          {'rtype': float, 'default': 0.},
            'gContXMean_x5_s2':          {'rtype': float, 'default': 0.},
            'gContYMean_x1_s2':          {'rtype': float, 'default': 0.},
            'gContYMean_x2_s2':          {'rtype': float, 'default': 0.},
            'gContYMean_x3_s2':          {'rtype': float, 'default': 0.},
            'gContYMean_x4_s2':          {'rtype': float, 'default': 0.},
            'gContYMean_x5_s2':          {'rtype': float, 'default': 0.},
            'gContLayerMean_x1_s2':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x2_s2':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x3_s2':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x4_s2':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x5_s2':      {'rtype': float, 'default': 0.},
            'gContXStd_x1_s2':           {'rtype': float, 'default': 0.},
            'gContXStd_x2_s2':           {'rtype': float, 'default': 0.},
            'gContXStd_x3_s2':           {'rtype': float, 'default': 0.},
            'gContXStd_x4_s2':           {'rtype': float, 'default': 0.},
            'gContXStd_x5_s2':           {'rtype': float, 'default': 0.},
            'gContYStd_x1_s2':           {'rtype': float, 'default': 0.},
            'gContYStd_x2_s2':           {'rtype': float, 'default': 0.},
            'gContYStd_x3_s2':           {'rtype': float, 'default': 0.},
            'gContYStd_x4_s2':           {'rtype': float, 'default': 0.},
            'gContYStd_x5_s2':           {'rtype': float, 'default': 0.},
            'gContLayerStd_x1_s2':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x2_s2':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x3_s2':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x4_s2':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x5_s2':       {'rtype': float, 'default': 0.},
            'gContEnergy_x1_s3':         {'rtype': float, 'default': 0.},
            'gContEnergy_x2_s3':         {'rtype': float, 'default': 0.},
            'gContEnergy_x3_s3':         {'rtype': float, 'default': 0.},
            'gContEnergy_x4_s3':         {'rtype': float, 'default': 0.},
            'gContEnergy_x5_s3':         {'rtype': float, 'default': 0.},
            'gContNHits_x1_s3':          {'rtype': int,   'default': 0 },
            'gContNHits_x2_s3':          {'rtype': int,   'default': 0 },
            'gContNHits_x3_s3':          {'rtype': int,   'default': 0 },
            'gContNHits_x4_s3':          {'rtype': int,   'default': 0 },
            'gContNHits_x5_s3':          {'rtype': int,   'default': 0 },
            'gContXMean_x1_s3':          {'rtype': float, 'default': 0.},
            'gContXMean_x2_s3':          {'rtype': float, 'default': 0.},
            'gContXMean_x3_s3':          {'rtype': float, 'default': 0.},
            'gContXMean_x4_s3':          {'rtype': float, 'default': 0.},
            'gContXMean_x5_s3':          {'rtype': float, 'default': 0.},
            'gContYMean_x1_s3':          {'rtype': float, 'default': 0.},
            'gContYMean_x2_s3':          {'rtype': float, 'default': 0.},
            'gContYMean_x3_s3':          {'rtype': float, 'default': 0.},
            'gContYMean_x4_s3':          {'rtype': float, 'default': 0.},
            'gContYMean_x5_s3':          {'rtype': float, 'default': 0.},
            'gContLayerMean_x1_s3':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x2_s3':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x3_s3':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x4_s3':      {'rtype': float, 'default': 0.},
            'gContLayerMean_x5_s3':      {'rtype': float, 'default': 0.},
            'gContXStd_x1_s3':           {'rtype': float, 'default': 0.},
            'gContXStd_x2_s3':           {'rtype': float, 'default': 0.},
            'gContXStd_x3_s3':           {'rtype': float, 'default': 0.},
            'gContXStd_x4_s3':           {'rtype': float, 'default': 0.},
            'gContXStd_x5_s3':           {'rtype': float, 'default': 0.},
            'gContYStd_x1_s3':           {'rtype': float, 'default': 0.},
            'gContYStd_x2_s3':           {'rtype': float, 'default': 0.},
            'gContYStd_x3_s3':           {'rtype': float, 'default': 0.},
            'gContYStd_x4_s3':           {'rtype': float, 'default': 0.},
            'gContYStd_x5_s3':           {'rtype': float, 'default': 0.},
            'gContLayerStd_x1_s3':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x2_s3':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x3_s3':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x4_s3':       {'rtype': float, 'default': 0.},
            'gContLayerStd_x5_s3':       {'rtype': float, 'default': 0.},
            # Outside RoC variables
            'oContEnergy_x1_s1':         {'rtype': float, 'default': 0.},
            'oContEnergy_x2_s1':         {'rtype': float, 'default': 0.},
            'oContEnergy_x3_s1':         {'rtype': float, 'default': 0.},
            'oContEnergy_x4_s1':         {'rtype': float, 'default': 0.},
            'oContEnergy_x5_s1':         {'rtype': float, 'default': 0.},
            'oContNHits_x1_s1':          {'rtype': int,   'default': 0 },
            'oContNHits_x2_s1':          {'rtype': int,   'default': 0 },
            'oContNHits_x3_s1':          {'rtype': int,   'default': 0 },
            'oContNHits_x4_s1':          {'rtype': int,   'default': 0 },
            'oContNHits_x5_s1':          {'rtype': int,   'default': 0 },
            'oContXMean_x1_s1':          {'rtype': float, 'default': 0.},
            'oContXMean_x2_s1':          {'rtype': float, 'default': 0.},
            'oContXMean_x3_s1':          {'rtype': float, 'default': 0.},
            'oContXMean_x4_s1':          {'rtype': float, 'default': 0.},
            'oContXMean_x5_s1':          {'rtype': float, 'default': 0.},
            'oContYMean_x1_s1':          {'rtype': float, 'default': 0.},
            'oContYMean_x2_s1':          {'rtype': float, 'default': 0.},
            'oContYMean_x3_s1':          {'rtype': float, 'default': 0.},
            'oContYMean_x4_s1':          {'rtype': float, 'default': 0.},
            'oContYMean_x5_s1':          {'rtype': float, 'default': 0.},
            'oContLayerMean_x1_s1':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x2_s1':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x3_s1':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x4_s1':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x5_s1':      {'rtype': float, 'default': 0.},
            'oContXStd_x1_s1':           {'rtype': float, 'default': 0.},
            'oContXStd_x2_s1':           {'rtype': float, 'default': 0.},
            'oContXStd_x3_s1':           {'rtype': float, 'default': 0.},
            'oContXStd_x4_s1':           {'rtype': float, 'default': 0.},
            'oContXStd_x5_s1':           {'rtype': float, 'default': 0.},
            'oContYStd_x1_s1':           {'rtype': float, 'default': 0.},
            'oContYStd_x2_s1':           {'rtype': float, 'default': 0.},
            'oContYStd_x3_s1':           {'rtype': float, 'default': 0.},
            'oContYStd_x4_s1':           {'rtype': float, 'default': 0.},
            'oContYStd_x5_s1':           {'rtype': float, 'default': 0.},
            'oContLayerStd_x1_s1':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x2_s1':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x3_s1':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x4_s1':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x5_s1':       {'rtype': float, 'default': 0.},
            'oContEnergy_x1_s2':         {'rtype': float, 'default': 0.},
            'oContEnergy_x2_s2':         {'rtype': float, 'default': 0.},
            'oContEnergy_x3_s2':         {'rtype': float, 'default': 0.},
            'oContEnergy_x4_s2':         {'rtype': float, 'default': 0.},
            'oContEnergy_x5_s2':         {'rtype': float, 'default': 0.},
            'oContNHits_x1_s2':          {'rtype': int,   'default': 0 },
            'oContNHits_x2_s2':          {'rtype': int,   'default': 0 },
            'oContNHits_x3_s2':          {'rtype': int,   'default': 0 },
            'oContNHits_x4_s2':          {'rtype': int,   'default': 0 },
            'oContNHits_x5_s2':          {'rtype': int,   'default': 0 },
            'oContXMean_x1_s2':          {'rtype': float, 'default': 0.},
            'oContXMean_x2_s2':          {'rtype': float, 'default': 0.},
            'oContXMean_x3_s2':          {'rtype': float, 'default': 0.},
            'oContXMean_x4_s2':          {'rtype': float, 'default': 0.},
            'oContXMean_x5_s2':          {'rtype': float, 'default': 0.},
            'oContYMean_x1_s2':          {'rtype': float, 'default': 0.},
            'oContYMean_x2_s2':          {'rtype': float, 'default': 0.},
            'oContYMean_x3_s2':          {'rtype': float, 'default': 0.},
            'oContYMean_x4_s2':          {'rtype': float, 'default': 0.},
            'oContYMean_x5_s2':          {'rtype': float, 'default': 0.},
            'oContLayerMean_x1_s2':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x2_s2':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x3_s2':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x4_s2':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x5_s2':      {'rtype': float, 'default': 0.},
            'oContXStd_x1_s2':           {'rtype': float, 'default': 0.},
            'oContXStd_x2_s2':           {'rtype': float, 'default': 0.},
            'oContXStd_x3_s2':           {'rtype': float, 'default': 0.},
            'oContXStd_x4_s2':           {'rtype': float, 'default': 0.},
            'oContXStd_x5_s2':           {'rtype': float, 'default': 0.},
            'oContYStd_x1_s2':           {'rtype': float, 'default': 0.},
            'oContYStd_x2_s2':           {'rtype': float, 'default': 0.},
            'oContYStd_x3_s2':           {'rtype': float, 'default': 0.},
            'oContYStd_x4_s2':           {'rtype': float, 'default': 0.},
            'oContYStd_x5_s2':           {'rtype': float, 'default': 0.},
            'oContLayerStd_x1_s2':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x2_s2':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x3_s2':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x4_s2':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x5_s2':       {'rtype': float, 'default': 0.},
            'oContEnergy_x1_s3':         {'rtype': float, 'default': 0.},
            'oContEnergy_x2_s3':         {'rtype': float, 'default': 0.},
            'oContEnergy_x3_s3':         {'rtype': float, 'default': 0.},
            'oContEnergy_x4_s3':         {'rtype': float, 'default': 0.},
            'oContEnergy_x5_s3':         {'rtype': float, 'default': 0.},
            'oContNHits_x1_s3':          {'rtype': int,   'default': 0 },
            'oContNHits_x2_s3':          {'rtype': int,   'default': 0 },
            'oContNHits_x3_s3':          {'rtype': int,   'default': 0 },
            'oContNHits_x4_s3':          {'rtype': int,   'default': 0 },
            'oContNHits_x5_s3':          {'rtype': int,   'default': 0 },
            'oContXMean_x1_s3':          {'rtype': float, 'default': 0.},
            'oContXMean_x2_s3':          {'rtype': float, 'default': 0.},
            'oContXMean_x3_s3':          {'rtype': float, 'default': 0.},
            'oContXMean_x4_s3':          {'rtype': float, 'default': 0.},
            'oContXMean_x5_s3':          {'rtype': float, 'default': 0.},
            'oContYMean_x1_s3':          {'rtype': float, 'default': 0.},
            'oContYMean_x2_s3':          {'rtype': float, 'default': 0.},
            'oContYMean_x3_s3':          {'rtype': float, 'default': 0.},
            'oContYMean_x4_s3':          {'rtype': float, 'default': 0.},
            'oContYMean_x5_s3':          {'rtype': float, 'default': 0.},
            'oContLayerMean_x1_s3':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x2_s3':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x3_s3':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x4_s3':      {'rtype': float, 'default': 0.},
            'oContLayerMean_x5_s3':      {'rtype': float, 'default': 0.},
            'oContXStd_x1_s3':           {'rtype': float, 'default': 0.},
            'oContXStd_x2_s3':           {'rtype': float, 'default': 0.},
            'oContXStd_x3_s3':           {'rtype': float, 'default': 0.},
            'oContXStd_x4_s3':           {'rtype': float, 'default': 0.},
            'oContXStd_x5_s3':           {'rtype': float, 'default': 0.},
            'oContYStd_x1_s3':           {'rtype': float, 'default': 0.},
            'oContYStd_x2_s3':           {'rtype': float, 'default': 0.},
            'oContYStd_x3_s3':           {'rtype': float, 'default': 0.},
            'oContYStd_x4_s3':           {'rtype': float, 'default': 0.},
            'oContYStd_x5_s3':           {'rtype': float, 'default': 0.},
            'oContLayerStd_x1_s3':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x2_s3':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x3_s3':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x4_s3':       {'rtype': float, 'default': 0.},
            'oContLayerStd_x5_s3':       {'rtype': float, 'default': 0.},
            # Quantities needed for BDT analysis
            'trigPass':                  {'rtype': int,   'default': 1 },
            'recoilPT':                  {'rtype': float, 'default': 0.},
            'discValue_bdt':             {'rtype': float, 'default': 0.5}
    }

    # Construct tree processes
    procs = []
    for gl, group in zip(group_labels, inlist):
        procs.append( manager.TreeProcess(event_process, group, ID=gl, tree_name='EcalVeto',
            pfreq=100) )

    # Process jobs
    for proc in procs:

        print('\nRunning %s'%(proc.ID))
        
        # Move into appropriate scratch dir
        os.chdir(proc.tmp_dir)

        # Make an output file and new tree (copied from input + discValue)
        proc.tfMaker = manager.TreeMaker(group_labels[procs.index(proc)]+'.root',\
                                         "EcalVeto",\
                                         branches_info,\
                                         outlist[procs.index(proc)]
                                         )

        # RUN
        proc.extrafs = [ proc.tfMaker.wq ] # Gets executed at the end of run()
        proc.run(maxEvents=maxEvent)

    # Remove scratch directory if there is one
    manager.rmScratch()

    print('\nDone!\n')


def event_process(self):

    # Feature list from input tree
    # Exp: feats = [ feat_value for feat_value in self.tree~ ]
    # Put all segmentation variables in for now (Take out the ones we won't need once
    # we make sure that all the python bdt stuff works)
    feats = [
            # Base variables
            self.tree.nReadoutHits              ,
            self.tree.summedDet                 ,
            self.tree.summedTightIso            ,
            self.tree.maxCellDep                ,
            self.tree.showerRMS                 ,
            self.tree.xStd                      ,
            self.tree.yStd                      ,
            self.tree.avgLayerHit               ,
            self.tree.stdLayerHit               ,
            self.tree.deepestLayerHit           ,
            self.tree.ecalBackEnergy            ,
            # MIP Tracking variables
            self.tree.straight4                 ,
            self.tree.firstNearPhLayer          ,
            self.tree.nNearPhHits               ,
            self.tree.fullElectronTerritoryHits ,
            self.tree.fullPhotonTerritoryHits   ,
            self.tree.fullTerritoryRatio        ,
            self.tree.electronTerritoryHits     ,
            self.tree.photonTerritoryHits       ,
            self.tree.TerritoryRatio            ,
            # Longitudinal segment variables
            self.tree.energy_s1                 ,
            self.tree.nHits_s1                  ,
            self.tree.xMean_s1                  ,
            self.tree.yMean_s1                  ,
            self.tree.layerMean_s1              ,
            self.tree.xStd_s1                   ,
            self.tree.yStd_s1                   ,
            self.tree.layerStd_s1               ,
            self.tree.energy_s2                 ,
            self.tree.nHits_s2                  ,
            self.tree.xMean_s2                  ,
            self.tree.yMean_s2                  ,
            self.tree.layerMean_s2              ,
            self.tree.xStd_s2                   ,
            self.tree.yStd_s2                   ,
            self.tree.layerStd_s2               ,
            self.tree.energy_s3                 ,
            self.tree.nHits_s3                  ,
            self.tree.xMean_s3                  ,
            self.tree.yMean_s3                  ,
            self.tree.layerMean_s3              ,
            self.tree.xStd_s3                   ,
            self.tree.yStd_s3                   ,
            self.tree.layerStd_s3               ,
            # Electron RoC variables
            self.tree.eContEnergy_x1_s1         ,
            self.tree.eContEnergy_x2_s1         ,
            self.tree.eContEnergy_x3_s1         ,
            self.tree.eContEnergy_x4_s1         ,
            self.tree.eContEnergy_x5_s1         ,
            self.tree.eContNHits_x1_s1          ,
            self.tree.eContNHits_x2_s1          ,
            self.tree.eContNHits_x3_s1          ,
            self.tree.eContNHits_x4_s1          ,
            self.tree.eContNHits_x5_s1          ,
            self.tree.eContXMean_x1_s1          ,
            self.tree.eContXMean_x2_s1          ,
            self.tree.eContXMean_x3_s1          ,
            self.tree.eContXMean_x4_s1          ,
            self.tree.eContXMean_x5_s1          ,
            self.tree.eContYMean_x1_s1          ,
            self.tree.eContYMean_x2_s1          ,
            self.tree.eContYMean_x3_s1          ,
            self.tree.eContYMean_x4_s1          ,
            self.tree.eContYMean_x5_s1          ,
            self.tree.eContLayerMean_x1_s1      ,
            self.tree.eContLayerMean_x2_s1      ,
            self.tree.eContLayerMean_x3_s1      ,
            self.tree.eContLayerMean_x4_s1      ,
            self.tree.eContLayerMean_x5_s1      ,
            self.tree.eContXStd_x1_s1           ,
            self.tree.eContXStd_x2_s1           ,
            self.tree.eContXStd_x3_s1           ,
            self.tree.eContXStd_x4_s1           ,
            self.tree.eContXStd_x5_s1           ,
            self.tree.eContYStd_x1_s1           ,
            self.tree.eContYStd_x2_s1           ,
            self.tree.eContYStd_x3_s1           ,
            self.tree.eContYStd_x4_s1           ,
            self.tree.eContYStd_x5_s1           ,
            self.tree.eContLayerStd_x1_s1       ,
            self.tree.eContLayerStd_x2_s1       ,
            self.tree.eContLayerStd_x3_s1       ,
            self.tree.eContLayerStd_x4_s1       ,
            self.tree.eContLayerStd_x5_s1       ,
            self.tree.eContEnergy_x1_s2         ,
            self.tree.eContEnergy_x2_s2         ,
            self.tree.eContEnergy_x3_s2         ,
            self.tree.eContEnergy_x4_s2         ,
            self.tree.eContEnergy_x5_s2         ,
            self.tree.eContNHits_x1_s2          ,
            self.tree.eContNHits_x2_s2          ,
            self.tree.eContNHits_x3_s2          ,
            self.tree.eContNHits_x4_s2          ,
            self.tree.eContNHits_x5_s2          ,
            self.tree.eContXMean_x1_s2          ,
            self.tree.eContXMean_x2_s2          ,
            self.tree.eContXMean_x3_s2          ,
            self.tree.eContXMean_x4_s2          ,
            self.tree.eContXMean_x5_s2          ,
            self.tree.eContYMean_x1_s2          ,
            self.tree.eContYMean_x2_s2          ,
            self.tree.eContYMean_x3_s2          ,
            self.tree.eContYMean_x4_s2          ,
            self.tree.eContYMean_x5_s2          ,
            self.tree.eContLayerMean_x1_s2      ,
            self.tree.eContLayerMean_x2_s2      ,
            self.tree.eContLayerMean_x3_s2      ,
            self.tree.eContLayerMean_x4_s2      ,
            self.tree.eContLayerMean_x5_s2      ,
            self.tree.eContXStd_x1_s2           ,
            self.tree.eContXStd_x2_s2           ,
            self.tree.eContXStd_x3_s2           ,
            self.tree.eContXStd_x4_s2           ,
            self.tree.eContXStd_x5_s2           ,
            self.tree.eContYStd_x1_s2           ,
            self.tree.eContYStd_x2_s2           ,
            self.tree.eContYStd_x3_s2           ,
            self.tree.eContYStd_x4_s2           ,
            self.tree.eContYStd_x5_s2           ,
            self.tree.eContLayerStd_x1_s2       ,
            self.tree.eContLayerStd_x2_s2       ,
            self.tree.eContLayerStd_x3_s2       ,
            self.tree.eContLayerStd_x4_s2       ,
            self.tree.eContLayerStd_x5_s2       ,
            self.tree.eContEnergy_x1_s3         ,
            self.tree.eContEnergy_x2_s3         ,
            self.tree.eContEnergy_x3_s3         ,
            self.tree.eContEnergy_x4_s3         ,
            self.tree.eContEnergy_x5_s3         ,
            self.tree.eContNHits_x1_s3          ,
            self.tree.eContNHits_x2_s3          ,
            self.tree.eContNHits_x3_s3          ,
            self.tree.eContNHits_x4_s3          ,
            self.tree.eContNHits_x5_s3          ,
            self.tree.eContXMean_x1_s3          ,
            self.tree.eContXMean_x2_s3          ,
            self.tree.eContXMean_x3_s3          ,
            self.tree.eContXMean_x4_s3          ,
            self.tree.eContXMean_x5_s3          ,
            self.tree.eContYMean_x1_s3          ,
            self.tree.eContYMean_x2_s3          ,
            self.tree.eContYMean_x3_s3          ,
            self.tree.eContYMean_x4_s3          ,
            self.tree.eContYMean_x5_s3          ,
            self.tree.eContLayerMean_x1_s3      ,
            self.tree.eContLayerMean_x2_s3      ,
            self.tree.eContLayerMean_x3_s3      ,
            self.tree.eContLayerMean_x4_s3      ,
            self.tree.eContLayerMean_x5_s3      ,
            self.tree.eContXStd_x1_s3           ,
            self.tree.eContXStd_x2_s3           ,
            self.tree.eContXStd_x3_s3           ,
            self.tree.eContXStd_x4_s3           ,
            self.tree.eContXStd_x5_s3           ,
            self.tree.eContYStd_x1_s3           ,
            self.tree.eContYStd_x2_s3           ,
            self.tree.eContYStd_x3_s3           ,
            self.tree.eContYStd_x4_s3           ,
            self.tree.eContYStd_x5_s3           ,
            self.tree.eContLayerStd_x1_s3       ,
            self.tree.eContLayerStd_x2_s3       ,
            self.tree.eContLayerStd_x3_s3       ,
            self.tree.eContLayerStd_x4_s3       ,
            self.tree.eContLayerStd_x5_s3       ,
            # Photon RoC variables
            self.tree.gContEnergy_x1_s1         ,
            self.tree.gContEnergy_x2_s1         ,
            self.tree.gContEnergy_x3_s1         ,
            self.tree.gContEnergy_x4_s1         ,
            self.tree.gContEnergy_x5_s1         ,
            self.tree.gContNHits_x1_s1          ,
            self.tree.gContNHits_x2_s1          ,
            self.tree.gContNHits_x3_s1          ,
            self.tree.gContNHits_x4_s1          ,
            self.tree.gContNHits_x5_s1          ,
            self.tree.gContXMean_x1_s1          ,
            self.tree.gContXMean_x2_s1          ,
            self.tree.gContXMean_x3_s1          ,
            self.tree.gContXMean_x4_s1          ,
            self.tree.gContXMean_x5_s1          ,
            self.tree.gContYMean_x1_s1          ,
            self.tree.gContYMean_x2_s1          ,
            self.tree.gContYMean_x3_s1          ,
            self.tree.gContYMean_x4_s1          ,
            self.tree.gContYMean_x5_s1          ,
            self.tree.gContLayerMean_x1_s1      ,
            self.tree.gContLayerMean_x2_s1      ,
            self.tree.gContLayerMean_x3_s1      ,
            self.tree.gContLayerMean_x4_s1      ,
            self.tree.gContLayerMean_x5_s1      ,
            self.tree.gContXStd_x1_s1           ,
            self.tree.gContXStd_x2_s1           ,
            self.tree.gContXStd_x3_s1           ,
            self.tree.gContXStd_x4_s1           ,
            self.tree.gContXStd_x5_s1           ,
            self.tree.gContYStd_x1_s1           ,
            self.tree.gContYStd_x2_s1           ,
            self.tree.gContYStd_x3_s1           ,
            self.tree.gContYStd_x4_s1           ,
            self.tree.gContYStd_x5_s1           ,
            self.tree.gContLayerStd_x1_s1       ,
            self.tree.gContLayerStd_x2_s1       ,
            self.tree.gContLayerStd_x3_s1       ,
            self.tree.gContLayerStd_x4_s1       ,
            self.tree.gContLayerStd_x5_s1       ,
            self.tree.gContEnergy_x1_s2         ,
            self.tree.gContEnergy_x2_s2         ,
            self.tree.gContEnergy_x3_s2         ,
            self.tree.gContEnergy_x4_s2         ,
            self.tree.gContEnergy_x5_s2         ,
            self.tree.gContNHits_x1_s2          ,
            self.tree.gContNHits_x2_s2          ,
            self.tree.gContNHits_x3_s2          ,
            self.tree.gContNHits_x4_s2          ,
            self.tree.gContNHits_x5_s2          ,
            self.tree.gContXMean_x1_s2          ,
            self.tree.gContXMean_x2_s2          ,
            self.tree.gContXMean_x3_s2          ,
            self.tree.gContXMean_x4_s2          ,
            self.tree.gContXMean_x5_s2          ,
            self.tree.gContYMean_x1_s2          ,
            self.tree.gContYMean_x2_s2          ,
            self.tree.gContYMean_x3_s2          ,
            self.tree.gContYMean_x4_s2          ,
            self.tree.gContYMean_x5_s2          ,
            self.tree.gContLayerMean_x1_s2      ,
            self.tree.gContLayerMean_x2_s2      ,
            self.tree.gContLayerMean_x3_s2      ,
            self.tree.gContLayerMean_x4_s2      ,
            self.tree.gContLayerMean_x5_s2      ,
            self.tree.gContXStd_x1_s2           ,
            self.tree.gContXStd_x2_s2           ,
            self.tree.gContXStd_x3_s2           ,
            self.tree.gContXStd_x4_s2           ,
            self.tree.gContXStd_x5_s2           ,
            self.tree.gContYStd_x1_s2           ,
            self.tree.gContYStd_x2_s2           ,
            self.tree.gContYStd_x3_s2           ,
            self.tree.gContYStd_x4_s2           ,
            self.tree.gContYStd_x5_s2           ,
            self.tree.gContLayerStd_x1_s2       ,
            self.tree.gContLayerStd_x2_s2       ,
            self.tree.gContLayerStd_x3_s2       ,
            self.tree.gContLayerStd_x4_s2       ,
            self.tree.gContLayerStd_x5_s2       ,
            self.tree.gContEnergy_x1_s3         ,
            self.tree.gContEnergy_x2_s3         ,
            self.tree.gContEnergy_x3_s3         ,
            self.tree.gContEnergy_x4_s3         ,
            self.tree.gContEnergy_x5_s3         ,
            self.tree.gContNHits_x1_s3          ,
            self.tree.gContNHits_x2_s3          ,
            self.tree.gContNHits_x3_s3          ,
            self.tree.gContNHits_x4_s3          ,
            self.tree.gContNHits_x5_s3          ,
            self.tree.gContXMean_x1_s3          ,
            self.tree.gContXMean_x2_s3          ,
            self.tree.gContXMean_x3_s3          ,
            self.tree.gContXMean_x4_s3          ,
            self.tree.gContXMean_x5_s3          ,
            self.tree.gContYMean_x1_s3          ,
            self.tree.gContYMean_x2_s3          ,
            self.tree.gContYMean_x3_s3          ,
            self.tree.gContYMean_x4_s3          ,
            self.tree.gContYMean_x5_s3          ,
            self.tree.gContLayerMean_x1_s3      ,
            self.tree.gContLayerMean_x2_s3      ,
            self.tree.gContLayerMean_x3_s3      ,
            self.tree.gContLayerMean_x4_s3      ,
            self.tree.gContLayerMean_x5_s3      ,
            self.tree.gContXStd_x1_s3           ,
            self.tree.gContXStd_x2_s3           ,
            self.tree.gContXStd_x3_s3           ,
            self.tree.gContXStd_x4_s3           ,
            self.tree.gContXStd_x5_s3           ,
            self.tree.gContYStd_x1_s3           ,
            self.tree.gContYStd_x2_s3           ,
            self.tree.gContYStd_x3_s3           ,
            self.tree.gContYStd_x4_s3           ,
            self.tree.gContYStd_x5_s3           ,
            self.tree.gContLayerStd_x1_s3       ,
            self.tree.gContLayerStd_x2_s3       ,
            self.tree.gContLayerStd_x3_s3       ,
            self.tree.gContLayerStd_x4_s3       ,
            self.tree.gContLayerStd_x5_s3       ,
            # Outside RoC variables
            self.tree.oContEnergy_x1_s1         ,
            self.tree.oContEnergy_x2_s1         ,
            self.tree.oContEnergy_x3_s1         ,
            self.tree.oContEnergy_x4_s1         ,
            self.tree.oContEnergy_x5_s1         ,
            self.tree.oContNHits_x1_s1          ,
            self.tree.oContNHits_x2_s1          ,
            self.tree.oContNHits_x3_s1          ,
            self.tree.oContNHits_x4_s1          ,
            self.tree.oContNHits_x5_s1          ,
            self.tree.oContXMean_x1_s1          ,
            self.tree.oContXMean_x2_s1          ,
            self.tree.oContXMean_x3_s1          ,
            self.tree.oContXMean_x4_s1          ,
            self.tree.oContXMean_x5_s1          ,
            self.tree.oContYMean_x1_s1          ,
            self.tree.oContYMean_x2_s1          ,
            self.tree.oContYMean_x3_s1          ,
            self.tree.oContYMean_x4_s1          ,
            self.tree.oContYMean_x5_s1          ,
            self.tree.oContLayerMean_x1_s1      ,
            self.tree.oContLayerMean_x2_s1      ,
            self.tree.oContLayerMean_x3_s1      ,
            self.tree.oContLayerMean_x4_s1      ,
            self.tree.oContLayerMean_x5_s1      ,
            self.tree.oContXStd_x1_s1           ,
            self.tree.oContXStd_x2_s1           ,
            self.tree.oContXStd_x3_s1           ,
            self.tree.oContXStd_x4_s1           ,
            self.tree.oContXStd_x5_s1           ,
            self.tree.oContYStd_x1_s1           ,
            self.tree.oContYStd_x2_s1           ,
            self.tree.oContYStd_x3_s1           ,
            self.tree.oContYStd_x4_s1           ,
            self.tree.oContYStd_x5_s1           ,
            self.tree.oContLayerStd_x1_s1       ,
            self.tree.oContLayerStd_x2_s1       ,
            self.tree.oContLayerStd_x3_s1       ,
            self.tree.oContLayerStd_x4_s1       ,
            self.tree.oContLayerStd_x5_s1       ,
            self.tree.oContEnergy_x1_s2         ,
            self.tree.oContEnergy_x2_s2         ,
            self.tree.oContEnergy_x3_s2         ,
            self.tree.oContEnergy_x4_s2         ,
            self.tree.oContEnergy_x5_s2         ,
            self.tree.oContNHits_x1_s2          ,
            self.tree.oContNHits_x2_s2          ,
            self.tree.oContNHits_x3_s2          ,
            self.tree.oContNHits_x4_s2          ,
            self.tree.oContNHits_x5_s2          ,
            self.tree.oContXMean_x1_s2          ,
            self.tree.oContXMean_x2_s2          ,
            self.tree.oContXMean_x3_s2          ,
            self.tree.oContXMean_x4_s2          ,
            self.tree.oContXMean_x5_s2          ,
            self.tree.oContYMean_x1_s2          ,
            self.tree.oContYMean_x2_s2          ,
            self.tree.oContYMean_x3_s2          ,
            self.tree.oContYMean_x4_s2          ,
            self.tree.oContYMean_x5_s2          ,
            self.tree.oContLayerMean_x1_s2      ,
            self.tree.oContLayerMean_x2_s2      ,
            self.tree.oContLayerMean_x3_s2      ,
            self.tree.oContLayerMean_x4_s2      ,
            self.tree.oContLayerMean_x5_s2      ,
            self.tree.oContXStd_x1_s2           ,
            self.tree.oContXStd_x2_s2           ,
            self.tree.oContXStd_x3_s2           ,
            self.tree.oContXStd_x4_s2           ,
            self.tree.oContXStd_x5_s2           ,
            self.tree.oContYStd_x1_s2           ,
            self.tree.oContYStd_x2_s2           ,
            self.tree.oContYStd_x3_s2           ,
            self.tree.oContYStd_x4_s2           ,
            self.tree.oContYStd_x5_s2           ,
            self.tree.oContLayerStd_x1_s2       ,
            self.tree.oContLayerStd_x2_s2       ,
            self.tree.oContLayerStd_x3_s2       ,
            self.tree.oContLayerStd_x4_s2       ,
            self.tree.oContLayerStd_x5_s2       ,
            self.tree.oContEnergy_x1_s3         ,
            self.tree.oContEnergy_x2_s3         ,
            self.tree.oContEnergy_x3_s3         ,
            self.tree.oContEnergy_x4_s3         ,
            self.tree.oContEnergy_x5_s3         ,
            self.tree.oContNHits_x1_s3          ,
            self.tree.oContNHits_x2_s3          ,
            self.tree.oContNHits_x3_s3          ,
            self.tree.oContNHits_x4_s3          ,
            self.tree.oContNHits_x5_s3          ,
            self.tree.oContXMean_x1_s3          ,
            self.tree.oContXMean_x2_s3          ,
            self.tree.oContXMean_x3_s3          ,
            self.tree.oContXMean_x4_s3          ,
            self.tree.oContXMean_x5_s3          ,
            self.tree.oContYMean_x1_s3          ,
            self.tree.oContYMean_x2_s3          ,
            self.tree.oContYMean_x3_s3          ,
            self.tree.oContYMean_x4_s3          ,
            self.tree.oContYMean_x5_s3          ,
            self.tree.oContLayerMean_x1_s3      ,
            self.tree.oContLayerMean_x2_s3      ,
            self.tree.oContLayerMean_x3_s3      ,
            self.tree.oContLayerMean_x4_s3      ,
            self.tree.oContLayerMean_x5_s3      ,
            self.tree.oContXStd_x1_s3           ,
            self.tree.oContXStd_x2_s3           ,
            self.tree.oContXStd_x3_s3           ,
            self.tree.oContXStd_x4_s3           ,
            self.tree.oContXStd_x5_s3           ,
            self.tree.oContYStd_x1_s3           ,
            self.tree.oContYStd_x2_s3           ,
            self.tree.oContYStd_x3_s3           ,
            self.tree.oContYStd_x4_s3           ,
            self.tree.oContYStd_x5_s3           ,
            self.tree.oContLayerStd_x1_s3       ,
            self.tree.oContLayerStd_x2_s3       ,
            self.tree.oContLayerStd_x3_s3       ,
            self.tree.oContLayerStd_x4_s3       ,
            self.tree.oContLayerStd_x5_s3       
    ]

    # Copy input tree feats to new tree
    for feat_name, feat_value in zip(self.tfMaker.branches_info, feats):

        # Condition to catch NaN bugs if they exist
        if math.isnan(feat_value):
            print('The problematic feature is: {}'.format(feat_name))
            self.tfMaker.branches[feat_name][0] = self.tfMaker.branches_info[feat_name]['default']
        else:
            self.tfMaker.branches[feat_name][0] = feat_value

    # Add the quantities needed for BDT analysis to the tree
    self.tfMaker.branches['trigPass'][0] = self.tree.trigPass
    self.tfMaker.branches['recoilPT'][0] = self.tree.recoilPT

    # Add prediction to new tree
    evtarray = np.array([feats])
    pred = float(model.predict(xgb.DMatrix(evtarray))[0])
    self.tfMaker.branches['discValue_bdt'][0] = pred

    # Fill new tree with current event values
    self.tfMaker.tree.Fill()

if __name__ == "__main__":
    main()
